name: Pester UnitTest on Ubuntu
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Perform a Pester test from the command-line
        shell: pwsh
        run: |
          Get-ChildItem -Path . -Recurse 
          Test-Path ./person.ps1 | Should -Be $true
          Test-Path ./tests/person.tests.ps1 | Should -Be $true
          Test-Path ./bankholidays.ps1 | Should -Be $true
          Test-Path ./tests/bankholidays.tests.ps1 | Should -Be $true
      - name: Perform a Pester test from the person.tests.ps1 file 
        shell: pwsh
        run: |
          Invoke-Pester ./tests/person.tests.ps1 -Passthru
      - name: Perform a Pester test from the bankhoildays.tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester ./tests/bankhoildays.tests.ps1 -Passthru
